# See https://help.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: 'npm'
    versioning-strategy: 'increase'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
