name: 'Changelog'

on:
  release:
    types:
      - 'created'
      - 'published'
  workflow_dispatch:

jobs:
  changelog:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4.0.0'
        with:
          ref: 'main'
      - name: 'Generate changelog'
        uses: 'rhysd/changelog-from-release/action@v3'
        with:
          file: 'CHANGELOG.md'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
