name: Changelog

on:
  # release:
  #   types:
  #     - created
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Changelog generator
      uses: dittrichlucas/changelog-generator@main
      with:
        token: ${{ github.token }}
        repo: ${{ github.repository }}

    - name: Print changelog to console
      run: cat CHANGELOG.md
