name: 'Test'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'

concurrency:
  group: 'test-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    name: 'Test'
    strategy:
      fail-fast: false
      matrix:
        version: [16, 18, 20]
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4.1.5'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4.0.2'
        with:
          node-version: '${{ matrix.version }}'
          cache: 'npm'
      - name: 'Install dependencies'
        run: 'npm ci'
      - name: 'Test'
        run: 'npm run test'

  type-test:
    name: 'Type test'
    strategy:
      fail-fast: false
      matrix:
        version: [16, 18, 20]
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4.1.5'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4.0.2'
        with:
          node-version: '${{ matrix.version }}'
          cache: 'npm'
      - name: 'Install dependencies'
        run: 'npm ci'
      - name: 'Type test'
        run: 'npm run type-test'

  lint:
    name: 'Lint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4.1.5'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4.0.2'
        with:
          node-version: 20
          cache: 'npm'
      - name: 'Install dependencies'
        run: 'npm ci'
      - name: 'Lint with ESLint'
        run: 'npm run lint:eslint'
      - name: 'Lint with Markdownlint'
        run: 'npm run lint:markdownlint'
      - name: 'Lint with Prettier'
        run: 'npm run lint:prettier'
      - name: 'Lint with yamllint'
        uses: 'ibiqlik/action-yamllint@v3'

  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4.1.5'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4.0.2'
        with:
          node-version: 20
          cache: 'npm'
      - name: 'Install dependencies'
        run: 'npm ci'
      - name: 'Build'
        run: 'npm run build'
